apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-base-image: us-east4-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python313
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-function-target: page_scraper_worker
    run.googleapis.com/build-image-uri: us-east4-docker.pkg.dev/vertex-ai-scraper-project/cloud-run-source-deploy/page-scraper-worker
    run.googleapis.com/build-name: projects/677825641273/locations/us-east4/builds/f2bd3f35-1964-4d6b-8f8d-8cf1a874b277
    run.googleapis.com/build-source-location: gs://run-sources-vertex-ai-scraper-project-us-east4/services/page-scraper-worker/1759510395.729000.zip#1759510396025642
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: 65e613ed-3607-456b-b09a-449b9966461a
    run.googleapis.com/urls: '["https://page-scraper-worker-677825641273.us-east4.run.app","https://page-scraper-worker-6eaa7aavea-uk.a.run.app"]'
    serving.knative.dev/creator: ogcreid@gmail.com
    serving.knative.dev/lastModifier: ogcreid@gmail.com
  creationTimestamp: '2025-09-27T23:50:19.484239Z'
  generation: 6
  labels:
    cloud.googleapis.com/location: us-east4
    run.googleapis.com/satisfiesPzs: 'true'
  name: page-scraper-worker
  namespace: '677825641273'
  resourceVersion: AAZAQ/R1sMQ
  selfLink: /apis/serving.knative.dev/v1/namespaces/677825641273/services/page-scraper-worker
  uid: 96e0faa9-ddda-4881-8c11-50801e3659a3
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/base-images: '{"page-scraper-worker-1":"us-east4-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python313"}'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: vertex-ai-scraper-project:us-east4:zoho-rag
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: 1436f458-2e94-47db-b68b-ef860e2649e0
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DB_INSTANCE
          value: vertex-ai-scraper-project:us-east4:zoho-rag
        - name: DB_PASS
          value: V%p]K$n<F1(|3ggJ
        - name: DB_USER
          value: postgres
        image: us-east4-docker.pkg.dev/vertex-ai-scraper-project/cloud-run-source-deploy/page-scraper-worker@sha256:0f35856b0c111103560f911fc1a49cac4bc26a19cdfc95d41818ce767576b3d2
        name: page-scraper-worker-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      runtimeClassName: run.googleapis.com/linux-base-image-update
      serviceAccountName: 677825641273-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://page-scraper-worker-6eaa7aavea-uk.a.run.app
  conditions:
  - lastTransitionTime: '2025-10-03T16:54:28.604100Z'
    status: 'True'
    type: Ready
  - severity: Info
    status: 'True'
    type: BaseImageValidated
  - lastTransitionTime: '2025-10-03T16:54:27.338365Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2025-10-03T16:54:28.570596Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: page-scraper-worker-00006-9gg
  latestReadyRevisionName: page-scraper-worker-00006-9gg
  observedGeneration: 6
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: page-scraper-worker-00006-9gg
  url: https://page-scraper-worker-6eaa7aavea-uk.a.run.app
