apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-base-image: us-east4-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python313
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-function-target: find_sitemaps_for_urls_http
    run.googleapis.com/build-image-uri: us-east4-docker.pkg.dev/vertex-ai-scraper-project/cloud-run-source-deploy/find-sitemaps
    run.googleapis.com/build-name: projects/677825641273/locations/us-east4/builds/a3322ca1-abef-42b6-893d-3a828ae32f61
    run.googleapis.com/build-source-location: gs://run-sources-vertex-ai-scraper-project-us-east4/services/find-sitemaps/1759620288.243000.zip#1759620288604761
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: 9612505a-9628-4423-824d-b7175ec0b68e
    run.googleapis.com/urls: '["https://find-sitemaps-677825641273.us-east4.run.app","https://find-sitemaps-6eaa7aavea-uk.a.run.app"]'
    serving.knative.dev/creator: ogcreid@gmail.com
    serving.knative.dev/lastModifier: ogcreid@gmail.com
  creationTimestamp: '2025-10-04T12:13:03.512080Z'
  generation: 13
  labels:
    cloud.googleapis.com/location: us-east4
    run.googleapis.com/satisfiesPzs: 'true'
  name: find-sitemaps
  namespace: '677825641273'
  resourceVersion: AAZAXYntsbk
  selfLink: /apis/serving.knative.dev/v1/namespaces/677825641273/services/find-sitemaps
  uid: 5ae0d2d6-935f-406a-bfcc-57b5b377e147
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/base-images: '{"find-sitemaps-1":"us-east4-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python313"}'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: vertex-ai-scraper-project:us-east4:zoho-rag
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: 30af89fa-4da7-46fa-b457-2dd400bb50c8
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DB_INSTANCE
          value: vertex-ai-scraper-project:us-east4:zoho-rag
        - name: DB_PASS
          value: V%p]K$n<F1(|3ggJ
        - name: DB_USER
          value: postgres
        - name: DB_NAME
          value: zoho_rag
        image: us-east4-docker.pkg.dev/vertex-ai-scraper-project/cloud-run-source-deploy/find-sitemaps@sha256:f48319f99c7a0bab5bec0651dabce2f22fee62eea1ebd9fb526983d61ccd88d9
        name: find-sitemaps-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      runtimeClassName: run.googleapis.com/linux-base-image-update
      serviceAccountName: 677825641273-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://find-sitemaps-6eaa7aavea-uk.a.run.app
  conditions:
  - lastTransitionTime: '2025-10-04T23:25:50.456249Z'
    status: 'True'
    type: Ready
  - severity: Info
    status: 'True'
    type: BaseImageValidated
  - lastTransitionTime: '2025-10-04T23:25:48.051707Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2025-10-04T23:25:50.410316Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: find-sitemaps-00013-wbh
  latestReadyRevisionName: find-sitemaps-00013-wbh
  observedGeneration: 13
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: find-sitemaps-00013-wbh
  url: https://find-sitemaps-6eaa7aavea-uk.a.run.app
