apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-base-image: us-east4-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python313
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-function-target: reset_pipeline_data
    run.googleapis.com/build-image-uri: us-east4-docker.pkg.dev/vertex-ai-scraper-project/cloud-run-source-deploy/reset-pipeline-data
    run.googleapis.com/build-name: projects/677825641273/locations/us-east4/builds/cd18af72-b706-4aa5-9306-b53dd74e06bb
    run.googleapis.com/build-source-location: gs://run-sources-vertex-ai-scraper-project-us-east4/services/reset-pipeline-data/1759261350.542000.zip#1759261350839069
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: 25919823-5b7f-4498-b324-a647dc0bf8cc
    run.googleapis.com/urls: '["https://reset-pipeline-data-677825641273.us-east4.run.app","https://reset-pipeline-data-6eaa7aavea-uk.a.run.app"]'
    serving.knative.dev/creator: ogcreid@gmail.com
    serving.knative.dev/lastModifier: ogcreid@gmail.com
  creationTimestamp: '2025-09-30T19:30:32.368243Z'
  generation: 5
  labels:
    cloud.googleapis.com/location: us-east4
    run.googleapis.com/satisfiesPzs: 'true'
  name: reset-pipeline-data
  namespace: '677825641273'
  resourceVersion: AAZACfcHc24
  selfLink: /apis/serving.knative.dev/v1/namespaces/677825641273/services/reset-pipeline-data
  uid: 366e2cea-4b66-4e80-a0e3-db9ec61d4256
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/base-images: '{"reset-pipeline-data-1":"us-east4-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python313"}'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: vertex-ai-scraper-project:us-east4:zoho-rag
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: 1813d289-718a-49c8-bd6c-877d0bd940d9
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DB_INSTANCE
          value: vertex-ai-scraper-project:us-east4:zoho-rag
        - name: DB_PASS
          value: V%p]K$n<F1(|3ggJ
        - name: DB_USER
          value: postgres
        image: us-east4-docker.pkg.dev/vertex-ai-scraper-project/cloud-run-source-deploy/reset-pipeline-data@sha256:0faf53000ee6016ec0b815a0090df7d9a064441be609969262ea1be465e20072
        name: reset-pipeline-data-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      runtimeClassName: run.googleapis.com/linux-base-image-update
      serviceAccountName: 677825641273-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://reset-pipeline-data-6eaa7aavea-uk.a.run.app
  conditions:
  - lastTransitionTime: '2025-09-30T19:43:23.607918Z'
    status: 'True'
    type: Ready
  - severity: Info
    status: 'True'
    type: BaseImageValidated
  - lastTransitionTime: '2025-09-30T19:43:22.270183Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2025-09-30T19:43:23.509340Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: reset-pipeline-data-00005-sgh
  latestReadyRevisionName: reset-pipeline-data-00005-sgh
  observedGeneration: 5
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: reset-pipeline-data-00005-sgh
  url: https://reset-pipeline-data-6eaa7aavea-uk.a.run.app
