apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-base-image: us-east4-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python313
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-function-target: rescrape_prep_http
    run.googleapis.com/build-image-uri: us-east4-docker.pkg.dev/vertex-ai-scraper-project/cloud-run-source-deploy/rescrape-prep
    run.googleapis.com/build-name: projects/677825641273/locations/us-east4/builds/f0cea6d5-ab57-4b4b-9931-ed429e2f5ceb
    run.googleapis.com/build-source-location: gs://run-sources-vertex-ai-scraper-project-us-east4/services/rescrape-prep/1762813029.572000.zip#1762813029880995
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: 96d0cad0-7747-47df-b748-963372c53881
    run.googleapis.com/urls: '["https://rescrape-prep-677825641273.us-east4.run.app","https://rescrape-prep-6eaa7aavea-uk.a.run.app"]'
    serving.knative.dev/creator: ogcreid@gmail.com
    serving.knative.dev/lastModifier: gcloud@fmpconnect.com
  creationTimestamp: '2025-10-03T13:34:01.865432Z'
  generation: 18
  labels:
    cloud.googleapis.com/location: us-east4
    run.googleapis.com/satisfiesPzs: 'true'
  name: rescrape-prep
  namespace: '677825641273'
  resourceVersion: AAZDROgsUAQ
  selfLink: /apis/serving.knative.dev/v1/namespaces/677825641273/services/rescrape-prep
  uid: 2ab3d99b-5f79-419d-80a9-5798e95b3147
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/base-images: '{"rescrape-prep-1":"us-east4-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python313"}'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: vertex-ai-scraper-project:us-east4:zoho-rag
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: e5622595-a198-4690-96fb-9d3cafc87776
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DB_INSTANCE
          value: vertex-ai-scraper-project:us-east4:zoho-rag
        - name: DB_NAME
          value: zoho_rag
        - name: DB_PASS
          value: V%p]K$n<F1(|3ggJ
        - name: DB_USER
          value: postgres
        - name: FILTER_URL_ENDPOINT
          value: https://filter-url-677825641273.us-east4.run.app
        image: us-east4-docker.pkg.dev/vertex-ai-scraper-project/cloud-run-source-deploy/rescrape-prep@sha256:0559b9ec359aa1509cbdd1e0417e00b09dd202c93f218488d8e55c8c18a4d6c6
        name: rescrape-prep-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      runtimeClassName: run.googleapis.com/linux-base-image-update
      serviceAccountName: 677825641273-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://rescrape-prep-6eaa7aavea-uk.a.run.app
  conditions:
  - lastTransitionTime: '2025-11-10T22:18:12.319236Z'
    status: 'True'
    type: Ready
  - severity: Info
    status: 'True'
    type: BaseImageValidated
  - lastTransitionTime: '2025-11-10T22:18:06.895330Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2025-11-10T22:18:12.283940Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: rescrape-prep-00017-2sd
  latestReadyRevisionName: rescrape-prep-00017-2sd
  observedGeneration: 18
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: rescrape-prep-00017-2sd
  url: https://rescrape-prep-6eaa7aavea-uk.a.run.app
